"""Rules, paths, and chokepoints.

CRITICAL: every edge carries the named rule that produced it and the evidence
supporting it. Both are validated here, so an edge without provenance cannot be
constructed. Edges are created by the deterministic rules engine only. The
language model never creates edges — it narrates paths that already exist.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, field_validator


class Rule(BaseModel):
    """One named inference rule. Rules are data so they can be cited and extended."""

    model_config = ConfigDict(frozen=True)

    name: str
    description: str
    preconditions: tuple[dict[str, str], ...]
    effect: str
    citation: str | None = None


class PathEdge(BaseModel):
    """One step in an attack path, with the rule and evidence that produced it."""

    model_config = ConfigDict(frozen=True)

    from_node: str
    to_node: str
    rule_name: str
    evidence: tuple[str, ...]
    description: str = ""

    @field_validator("rule_name")
    @classmethod
    def _rule_is_named(cls, value: str) -> str:
        if not value.strip():
            raise ValueError("rule_name must name the rule that produced this edge")
        return value

    @field_validator("evidence")
    @classmethod
    def _evidence_is_present(cls, value: tuple[str, ...]) -> tuple[str, ...]:
        if not value:
            raise ValueError("evidence must cite at least one observation or finding")
        return value


class AttackPath(BaseModel):
    """A proven chain of steps. Narration is attached strictly downstream."""

    model_config = ConfigDict(frozen=True)

    path_id: str
    edges: tuple[PathEdge, ...]
    score: float = 0.0
    # Generated by the model from the proven path above. Never the reverse.
    narration: str | None = None

    @field_validator("edges")
    @classmethod
    def _has_edges(cls, value: tuple[PathEdge, ...]) -> tuple[PathEdge, ...]:
        if not value:
            raise ValueError("an attack path needs at least one edge")
        return value


class Chokepoint(BaseModel):
    """One fix that breaks many paths. Ranked by how many."""

    finding_id: str
    paths_broken: list[str] = Field(default_factory=list)
    remediation: str
    rank: int
