"""
Shared data models. Everything crosses this boundary.

Two invariants:
  1. Every enriched field carries where it came from and how confident we are.
     No unattributed data anywhere in the system.
  2. Every score renders its own explanation. No opaque numbers.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum


class Source(str, Enum):
    """Where a piece of data came from. Required on enriched fields."""

    CVE_ORG = "cve.org"
    VULNRICHMENT = "cisa.vulnrichment"
    KEV = "cisa.kev"
    EPSS = "first.epss"
    NVD = "nvd"
    EUVD = "enisa.euvd"
    OSV = "osv.dev"
    GHSA = "github.advisories"
    EXPLOITDB = "exploitdb"
    METASPLOIT = "metasploit"
    BRON = "bron"
    DERIVED = "derived"          # computed by us — always label it
    SCANNER = "scanner"


class Confidence(str, Enum):
    HIGH = "high"        # authoritative source, exact match
    MEDIUM = "medium"    # secondary source, or fuzzy version match
    LOW = "low"          # inferred, derived, or heuristic


@dataclass
class Provenance:
    """Attached to every enriched value. Non-optional by design."""

    source: Source
    confidence: Confidence
    retrieved_at: datetime
    note: str | None = None


@dataclass
class Asset:
    """A host, service, or application discovered during a scan."""

    asset_id: str
    hostname: str | None
    ip: str | None
    ports: list[int] = field(default_factory=list)
    services: list[dict] = field(default_factory=list)
    # Identity resolution: six scanners describe one host six ways
    aliases: list[str] = field(default_factory=list)


@dataclass
class Finding:
    """One vulnerability on one asset, as reported by one scanner."""

    finding_id: str
    asset_id: str
    scanner: str
    cve_ids: list[str] = field(default_factory=list)
    title: str = ""
    description: str = ""
    raw: str = ""                                  # original tool output, for provenance
    detected_at: datetime | None = None
    # Populated by services.enrichment, never by the scanner adapter
    enrichment: dict[str, Provenance] = field(default_factory=dict)


@dataclass
class ScoreComponent:
    """One input to the Exposure Risk Score, with its reasoning."""

    name: str
    value: float
    weight: float
    explanation: str
    provenance: Provenance


@dataclass
class ExposureRiskScore:
    """Composite risk. Must always be able to explain itself."""

    value: float
    components: list[ScoreComponent]

    def explain(self) -> str:
        lines = [f"Exposure Risk Score: {self.value:.2f}", ""]
        for c in self.components:
            lines.append(
                f"  {c.name}: {c.value:.2f} (weight {c.weight:.2f}) — {c.explanation}"
                f"  [{c.provenance.source.value}, {c.provenance.confidence.value}]"
            )
        return "\n".join(lines)


@dataclass
class PathEdge:
    """
    One step in an attack path.

    CRITICAL: every edge must carry the scan fact and the named rule that produced it.
    Edges are created by the deterministic rules engine only. The LLM never creates edges.
    """

    from_node: str
    to_node: str
    rule_name: str               # the named rule that fired
    evidence: list[str]          # finding_ids / fact ids supporting this edge
    description: str = ""


@dataclass
class AttackPath:
    path_id: str
    edges: list[PathEdge]
    score: float = 0.0
    # Generated by the LLM from the proven path above. Never the reverse.
    narration: str | None = None
